# 1D Array

In [1]:
import numpy as np               #alias np here for numpy

In [2]:
#checking numpy version
np.__version__

'1.23.5'

In [3]:
a=np.array(87)   #single item in paranthesis without square [] brackets.
print(a),a.ndim

87


(None, 0)

In [4]:
a=np.array(25)   #single item in paranthesis without square [] brackets.
print(a) , a.shape

25


(None, ())

In [5]:
a=np.array(25)   #single item in paranthesis without square [] brackets.
print(a) , a.size

25


(None, 1)

In [6]:
a=np.array(42)
d1=np.array([23,43])
print([a,d1])


[array(42), array([23, 43])]


In [7]:
a=np.array(42)
d1=np.array([23,43])
print([a,d1]),a.ndim, a.shape, d1.ndim, d1.shape

[array(42), array([23, 43])]


(None, 0, (), 1, (2,))

In [8]:
l = [12,43,24,29,56,87]
array = np.array(l)
a.ndim, a.shape , a.size


(0, (), 1)

In [9]:
#heterogeneous
hetero=np.array([12,"akash",True])
print("heterogeous-" ,hetero)

#homogeneous
homo = np.array([11,22,33,44])
print("homogenous-" , homo)

heterogeous- ['12' 'akash' 'True']
homogenous- [11 22 33 44]


In [10]:
tuple_arr= {1,3,4455,8,65,4,24}
a.ndim, type(a), a.size

(0, numpy.ndarray, 1)

In [11]:
#homogeneous
homo = np.array([11,22,33,44])
a.size , type(a) , a.dtype

(1, numpy.ndarray, dtype('int32'))

In [71]:
# create array with list, tuple, dictionary, set , string with different data types
list_arr=[1,22,33,11,43,56,4]
tuple_arr=(1,3,4455,8,65,4,24) 
set_arr= {22,33,44,55,66,2,9}
dict_arr={1:100,2:200,3:'Truba'}
str_arr='np','numpy', 'pandas', 'matplotlib', 'seaborn'

In [72]:
l_a=np.array(list_arr)
print('list_a',l_a)
l_a

list_a [ 1 22 33 11 43 56  4]


array([ 1, 22, 33, 11, 43, 56,  4])

In [73]:
dict_arr={1:100,2:200,3:'Truba'}
a.ndim, a.shape, a.size , a.dtype

(4, (2, 2, 2, 25), 200, dtype('int32'))

In [74]:
s_t=np.array(set_arr)
print('set_a',s_t)
s_t


set_a {33, 66, 2, 22, 55, 9, 44}


array({33, 66, 2, 22, 55, 9, 44}, dtype=object)

In [75]:
l=[1,22,33,11,43,56,4]
print('list-',l, type(l))
print('--------------------------------------------')
arr_1d=np.array([1,22,33,11,43,56,4])
print('array-',arr_1d,',dimension-',arr_1d.ndim,',type-',type(arr_1d))
print('dtype-',arr_1d.dtype,'Size-',arr_1d.size,'shape-',arr_1d.shape)

list- [1, 22, 33, 11, 43, 56, 4] <class 'list'>
--------------------------------------------
array- [ 1 22 33 11 43 56  4] ,dimension- 1 ,type- <class 'numpy.ndarray'>
dtype- int32 Size- 7 shape- (7,)


In [76]:
# import sys - get size of, 
l=[1,22,33,11,43,56,4]
arr=np.array([1,22,33,11,43,56,4],dtype='int64')
print('type(list)-',type(l))
print('type(array)-',type(arr))
print(l)
print(arr)
import sys
print('list size in  bytes-',sys.getsizeof(1)*len(l))     
print('array size in bytes-',sys.getsizeof(arr))     # bytes
print(arr.itemsize)
print(arr.size)
print(len(arr))
print(arr.itemsize*arr.size)    # bytes
aaa=arr.tolist()
aaa

type(list)- <class 'list'>
type(array)- <class 'numpy.ndarray'>
[1, 22, 33, 11, 43, 56, 4]
[ 1 22 33 11 43 56  4]
list size in  bytes- 196
array size in bytes- 168
8
7
7
56


[1, 22, 33, 11, 43, 56, 4]

# 2D Array

In [77]:
z=np.array([[]])
print(z.ndim)

2


In [78]:
l=[[1,2,233,44,55],[33,44,55,22,11]]
arr_2d=np.array([[1,2,233,44,55],[33,44,55,22,11]])
a.ndim,  a.shape, 1,arr_2d

(4,
 (2, 2, 2, 25),
 1,
 array([[  1,   2, 233,  44,  55],
        [ 33,  44,  55,  22,  11]]))

In [79]:
print('dimension-',arr_2d.ndim,',type-',type(arr_2d))
print('dtype-',arr_2d.dtype,'Size-',arr_2d.size,'shape-',arr_2d.shape)

dimension- 2 ,type- <class 'numpy.ndarray'>
dtype- int32 Size- 10 shape- (2, 5)


In [80]:
a = [[1,2,3],[4,5,6],[8,9,0]]
arr_2d=np.array([[1,2,3],[4,5,6],[8,9,0]])
arr_2d.ndim, 1,arr_2d , arr_2d.shape, arr_2d.size

(2,
 1,
 array([[1, 2, 3],
        [4, 5, 6],
        [8, 9, 0]]),
 (3, 3),
 9)

In [81]:
print('dimension-',arr_2d.ndim,',type-',type(arr_2d))
print('dtype-',arr_2d.dtype,'Size-',arr_2d.size,'shape-',arr_2d.shape)

dimension- 2 ,type- <class 'numpy.ndarray'>
dtype- int32 Size- 9 shape- (3, 3)


# 3D Array

In [82]:
arr_3d=np.array([[[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]]])
arr_3d

array([[[ 1, 22,  3,  3],
        [ 4,  5,  6,  7]],

       [[ 1, 22,  3,  3],
        [ 4,  5,  6,  7]],

       [[ 1, 22,  3,  3],
        [ 4,  5,  6,  7]],

       [[ 1, 22,  3,  3],
        [ 4,  5,  6,  7]],

       [[ 1, 22,  3,  3],
        [ 4,  5,  6,  7]],

       [[ 1, 22,  3,  3],
        [ 4,  5,  6,  7]]])

In [83]:
print('dimension-',arr_3d.ndim,',type-',type(arr_3d))
print('dtype-',arr_3d.dtype,'Size-',arr_3d.size,'shape-',arr_3d.shape)

dimension- 3 ,type- <class 'numpy.ndarray'>
dtype- int32 Size- 48 shape- (6, 2, 4)


In [84]:
#np.zeros(), np.ones(), np.empty(),
#np.arange(), np.linspace(), dtype()
a_z=np.zeros(100)
a_z_reshape=a_z.reshape(2,50)
print(a_z_reshape,a_z_reshape.ndim)
print('------------------------------------------')
print(a_z,a_z.ndim)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]] 2
------------------------------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.] 1


In [85]:
# changes will be in implemented variable not stored in assigned variable
a_z=np.zeros(100) 
a_z_resize=a_z.resize(2,50)
print(a_z_resize) # assigned variable 
print(a_z) # function implemented variable

None
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]]


In [86]:
d4=np.array([
    
                [[[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]]],
    
                [[[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]]],
    
                [[[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]]],
    
                [[[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]],
                 [[1,22,3,3],[4,5,6,7]]]])

In [87]:
print('dimension-',d4.ndim,',type-',type(d4))
print('dtype-',d4.dtype,'Size-',d4.size,'shape-',d4.shape)

dimension- 4 ,type- <class 'numpy.ndarray'>
dtype- int32 Size- 192 shape- (4, 6, 2, 4)


In [88]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [89]:
a1=np.arange(1,10,8)
print(a1)

[1 9]


In [90]:
a=np.ones(8)
a

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [91]:
a=np.zeros(9)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [92]:
a=np.zeros(9,dtype="int8")
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [93]:
a=np.zeros(9,dtype="8int8")
a

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [94]:
a=np.linspace(4,10, num=5)
a

array([ 4. ,  5.5,  7. ,  8.5, 10. ])

In [95]:
import random
a= np.random.randint(1,500,500)
a

array([102,  66, 347, 419, 189, 229, 489, 255, 239, 485, 264, 488, 259,
       113, 360, 395, 187, 351, 458, 212, 174,  48, 402, 226,  36, 372,
       116,  94, 118,  50, 270, 367, 275, 175, 431, 430,  98,  29, 294,
       144, 396, 374, 198, 155,  59,   3, 372, 118,  97,  18, 161, 309,
       488, 414,  63, 107, 375, 452, 357, 336, 399, 175, 337, 165, 330,
       235, 305, 142, 191, 228, 289, 420, 209, 457, 185, 115, 261, 171,
       331, 326, 328, 367, 241, 100, 489, 342, 458, 328, 484, 251, 165,
       123, 254, 257, 483, 385, 232,  70, 385,  58, 393, 103, 366, 190,
       138, 495,  38, 334, 452, 489, 377, 432, 390,  74, 263, 359, 103,
       360, 227,  12, 312, 416,  43, 403, 193, 347, 237, 278,  30, 237,
       343, 468, 258, 311, 495, 232, 222, 266,  78, 367, 355, 111, 179,
       129, 197,  65, 206, 117, 466, 371, 205, 456, 195, 295, 274,  53,
       396, 239, 497, 192, 264, 387, 290, 422, 429, 328, 221, 169,   3,
       499, 197, 434,  85,  97,  75, 494, 116, 124, 376, 439, 19

In [96]:
a=np.full((12,12,43) ,55) #np.full((dimensions,columns,row))
a

array([[[55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55],
        ...,
        [55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55]],

       [[55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55],
        ...,
        [55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55]],

       [[55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55],
        ...,
        [55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55]],

       ...,

       [[55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55],
        ...,
        [55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55, 55],
        [55, 55, 55, ..., 55, 55

In [97]:
a=np.full((2), 20) #1D
a

array([20, 20])

In [98]:
a=np.full((5,6,4,3,1), 12) #5D
a

array([[[[[12],
          [12],
          [12]],

         [[12],
          [12],
          [12]],

         [[12],
          [12],
          [12]],

         [[12],
          [12],
          [12]]],


        [[[12],
          [12],
          [12]],

         [[12],
          [12],
          [12]],

         [[12],
          [12],
          [12]],

         [[12],
          [12],
          [12]]],


        [[[12],
          [12],
          [12]],

         [[12],
          [12],
          [12]],

         [[12],
          [12],
          [12]],

         [[12],
          [12],
          [12]]],


        [[[12],
          [12],
          [12]],

         [[12],
          [12],
          [12]],

         [[12],
          [12],
          [12]],

         [[12],
          [12],
          [12]]],


        [[[12],
          [12],
          [12]],

         [[12],
          [12],
          [12]],

         [[12],
          [12],
          [12]],

         [[12],
          [12],
          

In [99]:
a=np.full((5,3,1), 12) #3D
a,a.shape

(array([[[12],
         [12],
         [12]],
 
        [[12],
         [12],
         [12]],
 
        [[12],
         [12],
         [12]],
 
        [[12],
         [12],
         [12]],
 
        [[12],
         [12],
         [12]]]),
 (5, 3, 1))

In [100]:
a=np.zeros(100)
a_reshape = a.reshape(2,50)
print(a_reshape ,a.ndim)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0.]] 1


In [101]:
a=np.ones(100)
a_reshape = a.reshape(2,50)
print(a_reshape ,a.ndim)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]] 1


In [102]:
a=np.empty(100)
a_reshape = a.reshape(2,50)
print(a_reshape ,a.ndim)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]] 1


In [103]:
a=np.zeros(100).reshape(2,2,25)
a , a.ndim

(array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.]]]),
 3)

In [104]:
a=np.zeros(200).reshape(2,2,2,25)
a , a.ndim

(array([[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],
 
 
        [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
           0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]]]),


In [105]:
a=np.zeros(200).reshape(1,2,2,2,25)
a , a.ndim

(array([[[[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
          [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],
 
 
         [[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
          [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
           [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
            0., 0., 0., 0., 0., 0., 0., 0

In [106]:
a=np.arange(0,200).reshape(1,2,2,2,25)
a , a.ndim

(array([[[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
             12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
             24],
           [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
             37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
             49]],
 
          [[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
             62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
             74],
           [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,
             87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
             99]]],
 
 
         [[[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
            112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
            124],
           [125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136,
            137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
            149]],
 
          [[150,

In [107]:
import random
a=np.random.randint(0,100,200).reshape(2,2,2,25)
a , a.ndim

(array([[[[11,  7, 62, 11, 64, 44, 90, 98, 24, 72, 25, 49, 78, 96,  9,
           93,  8, 33, 95, 19, 84,  5, 52, 29, 13],
          [20, 92, 27, 15, 39, 20, 80,  5, 36, 98, 28, 89, 40, 58, 69,
            7, 81, 34, 75, 56, 85, 57, 60,  6, 79]],
 
         [[82, 11, 53, 54, 73, 55, 36, 59, 88, 80,  1, 11, 15, 60, 65,
            1, 67,  9, 88, 68, 38, 92, 46, 40, 58],
          [75, 88, 18, 30, 86, 77, 72, 33, 96, 32,  5, 92, 79, 37, 46,
           90, 16, 57, 95, 21, 27, 39, 45, 45, 13]]],
 
 
        [[[11, 26, 26, 70, 55, 62, 95, 59, 69, 39, 64, 48, 31, 66, 43,
           76, 77, 60, 47, 41,  7,  0, 55, 56, 37],
          [ 9, 67, 68, 72, 84, 32, 93, 26, 28, 81, 14, 19, 39, 64,  3,
           90, 54, 45, 31, 45, 27, 33, 30, 43, 42]],
 
         [[30, 63, 87, 16,  3, 56, 71, 11, 11, 74, 54,  6,  7, 72,  2,
           64, 41, 56, 50, 50, 49, 45, 26, 98,  3],
          [60, 24, 60, 67, 51, 89, 98,  2, 87, 98, 39, 75, 51, 80, 62,
           25, 61, 86, 78, 75, 61, 29, 53, 99,  1]]]]),


In [108]:
a=np.arange(25)
a[[3]]
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [109]:
a=np.arange(25)
a,print(a[5:12])

[ 5  6  7  8  9 10 11]


(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]),
 None)

In [110]:
a=np.arange(2,25)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24])

In [111]:
import random
a=np.random.randint(1,10,10).reshape(2,5)
print(a)

[[6 2 5 3 1]
 [2 5 3 4 4]]


In [112]:
a=np.full((5,5,5),5)
a

array([[[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]]])

In [113]:
a=np.arange(100).reshape(2,2,25)
a

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
         41, 42, 43, 44, 45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
         66, 67, 68, 69, 70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
         91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [114]:
a[[1],[1],[14]]

array([89])

In [115]:
a[[0],[0],[4]]

array([4])

In [116]:
a=np.arange(200).reshape(2,2,2,25)
a

array([[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
           12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
           24],
         [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
           37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
           49]],

        [[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
           62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
           74],
         [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,
           87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
           99]]],


       [[[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
          112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
          124],
         [125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136,
          137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
          149]],

        [[150, 151, 152, 153, 154, 155, 156, 157, 158, 1

In [117]:
a[[0],[0],[0],[4]]

array([4])

In [118]:
a[[1],[1],[1],[3]]

array([178])

In [119]:
a=np.arange(200).reshape(2,2,2,25)
a

array([[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
           12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
           24],
         [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
           37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
           49]],

        [[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
           62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
           74],
         [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,
           87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
           99]]],


       [[[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
          112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
          124],
         [125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136,
          137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
          149]],

        [[150, 151, 152, 153, 154, 155, 156, 157, 158, 1

In [120]:
a,a[1][1][0:12]

(array([[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
            12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
            24],
          [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
            37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
            49]],
 
         [[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
            62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
            74],
          [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,
            87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
            99]]],
 
 
        [[[100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
           112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
           124],
          [125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136,
           137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148,
           149]],
 
         [[150, 151, 152, 153, 154

In [121]:
a[1][1][0:1,0:14]

array([[150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
        163]])

In [122]:
n18=a[a>500]
n18, type(n18)

(array([], dtype=int32), numpy.ndarray)

In [123]:
s_a=a[a<500]
s_a,type(s_a)

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
        143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
        156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177

In [124]:
s_c=a[a%2==0]
s_c,a

(array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
         26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
         52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
         78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
        104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
        130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
        156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
        182, 184, 186, 188, 190, 192, 194, 196, 198]),
 array([[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
            12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
            24],
          [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,
            37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
            49]],
 
         [[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
            62,  63,  64,  65,  66,  67,  

In [125]:
a.argsort(axis=1)

array([[[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1]]],


       [[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1]]]], dtype=int64)

In [126]:
t_a=np.array(tuple_arr)
print('tuple_a',t_a)
t_a

tuple_a [   1    3 4455    8   65    4   24]


array([   1,    3, 4455,    8,   65,    4,   24])

In [127]:
s_t=np.array(set_arr)
print('set_a',s_t)
s_t

set_a {33, 66, 2, 22, 55, 9, 44}


array({33, 66, 2, 22, 55, 9, 44}, dtype=object)

In [128]:
d_t=np.array(dict_arr)
print('dict_a',d_t)
d_t

dict_a {1: 100, 2: 200, 3: 'Truba'}


array({1: 100, 2: 200, 3: 'Truba'}, dtype=object)

In [129]:
s_t=np.array(str_arr)
print('string_a',s_t)
s_t

string_a ['np' 'numpy' 'pandas' 'matplotlib' 'seaborn']


array(['np', 'numpy', 'pandas', 'matplotlib', 'seaborn'], dtype='<U10')

# Method 2 - np.array({([value1,value2,value3])}) -

In [130]:
# create array with list, tuple, dictionary, set , string with different data types
list_arr=np.array([1,22,33,11,43,56,4])
tuple_arr=np.array((1,3,4455,8,65,4,24))
set_arr=np.array({22,33,44,55,66,2,9})
dict_arr=np.array({1:100,2:200,3:'Truba'})
str_arr=np.array(('np','numpy', 'pandas', 'matplotlib', 'seaborn'))
list_arr,tuple_arr,set_arr,dict_arr,str_arr

(array([ 1, 22, 33, 11, 43, 56,  4]),
 array([   1,    3, 4455,    8,   65,    4,   24]),
 array({33, 66, 2, 22, 55, 9, 44}, dtype=object),
 array({1: 100, 2: 200, 3: 'Truba'}, dtype=object),
 array(['np', 'numpy', 'pandas', 'matplotlib', 'seaborn'], dtype='<U10'))

# Check array's dimension, type, datatype, size, shape

In [131]:
l=[100,322,343,711,430,56,40]
print('list-',l, type(l))
print('--------------------------------------------')
arr_1d=np.array([100,322,343,711,430,56,40])
print('array-',arr_1d,',dimension-',arr_1d.ndim,',type-',type(arr_1d))
print('dtype-',arr_1d.dtype,'Size-',arr_1d.size,'shape-',arr_1d.shape)

list- [100, 322, 343, 711, 430, 56, 40] <class 'list'>
--------------------------------------------
array- [100 322 343 711 430  56  40] ,dimension- 1 ,type- <class 'numpy.ndarray'>
dtype- int32 Size- 7 shape- (7,)


In [132]:
# import sys - get size of,
l=[100,322,343,711,430,56,40]
arr=np.array([100,322,343,711,430,56,40],dtype='int64')
print('type(list)-',type(l))
print('type(array)-',type(arr))
print(l)
print(arr)
import sys
print('list size in bytes-',sys.getsizeof(1)*len(l))
print('array size in bytes-',sys.getsizeof(arr)) # bytes
print(arr.itemsize)
print(arr.size)
print(len(arr))
print(arr.itemsize*arr.size) # bytes
aaa=arr.tolist()
aaa

type(list)- <class 'list'>
type(array)- <class 'numpy.ndarray'>
[100, 322, 343, 711, 430, 56, 40]
[100 322 343 711 430  56  40]
list size in bytes- 196
array size in bytes- 168
8
7
7
56


[100, 322, 343, 711, 430, 56, 40]

# 5 dimensional array

In [133]:
arr_5d=np.array([[
[[[100,322,343,711],[421,513,64,75]],[[100,322,343,711],[421,513,64,75]]]],
[
[[[100,322,343,711],[421,513,64,75]],[[100,322,343,711],[421,513,64,75]]]]])
arr_5d

array([[[[[100, 322, 343, 711],
          [421, 513,  64,  75]],

         [[100, 322, 343, 711],
          [421, 513,  64,  75]]]],



       [[[[100, 322, 343, 711],
          [421, 513,  64,  75]],

         [[100, 322, 343, 711],
          [421, 513,  64,  75]]]]])

In [134]:
print('dimension-',arr_5d.ndim,',type-',type(arr_5d))
print('dtype-',arr_5d.dtype,'Size-',arr_5d.size,'shape-',arr_5d.shape)

dimension- 5 ,type- <class 'numpy.ndarray'>
dtype- int32 Size- 32 shape- (2, 1, 2, 2, 4)


# High dimensional array

In [135]:
arr_6d=np.array([12,32,34],ndmin=6)
print(arr_6d)
print('number of Dimensions:',arr_6d.ndim)

[[[[[[12 32 34]]]]]]
number of Dimensions: 6


In [136]:
print('dimension-',arr_6d.ndim,',type-',type(arr_6d))
print('dtype-',arr_6d.dtype,'Size-',arr_6d.size,'shape-',arr_6d.shape)

dimension- 6 ,type- <class 'numpy.ndarray'>
dtype- int32 Size- 3 shape- (1, 1, 1, 1, 1, 3)


# Other funtions for creating arrays

In [140]:
# np.array([value1,value2,value3])
acm1_1=np.array([81,92,3,94,95])
print('acm1_1-',acm1_1)
list_=[81,92,3,94,95]
acm1_2=np.array(list_)
print('acm1_2-',acm1_2)

acm1_1- [81 92  3 94 95]
acm1_2- [81 92  3 94 95]


In [144]:
#acm= array create methods
# np.arange(value)
acm2_1=np.arange(6)
print('acm2_1',acm2_1)
acm2_2=np.arange(1,10,5) # np.arange(value[start],value[end],value[step])
print('acm2_2',acm2_2)

acm2_1 [0 1 2 3 4 5]
acm2_2 [1 6]


In [146]:
# np.ones()
acm3=np.ones(9)
acm3

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [147]:
# np.zeros()
acm4=np.zeros(190)
acm4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [151]:
# np.empty()
acm5=np.empty(20)
acm5

array([8.47802504e-312, 5.68175493e-322, 0.00000000e+000, 0.00000000e+000,
       1.05695422e-307, 1.16096346e-028, 9.82205649e+252, 1.11789342e+253,
       3.81388254e+180, 1.96626212e-062, 1.09623615e-153, 3.18539647e-120,
       5.97185003e+175, 2.19172373e+136, 1.09623615e-153, 2.28747304e+199,
       3.54393007e+246, 8.25373440e-048, 9.15948202e+135, 4.45041934e-307])

In [154]:
# np.linspace()
acm6=np.linspace(8,10 ,num=8 ) # np.linspace(start,end,num= value_ammounts)
acm6

array([ 8.        ,  8.28571429,  8.57142857,  8.85714286,  9.14285714,
        9.42857143,  9.71428571, 10.        ])

In [155]:
#np.arrange()
acm7=np.arange(1,8,2) # np.arange(value[start],value[end],value[step])
acm7

array([1, 3, 5, 7])

In [156]:
# np.random.randint()
import random # here we importing random module
acm8=np.random.randint(1,340,340) # (value[start],value[end],value[amount])
acm8

array([ 52,  36, 109, 297, 154, 163, 306,  50, 288, 214,  45, 224, 291,
       274, 273, 294, 128, 165, 107, 329, 247, 186, 196, 289, 140, 194,
       107, 135, 232, 201, 256, 279, 169,  52,  52, 249, 323,  46,  78,
       260,   4, 213, 199,  57, 203,  83, 251, 220, 191, 169, 134, 258,
         2, 228, 227,  65, 188, 174, 139,  77,  77, 168,  30,  11, 114,
        23,  14, 332, 175, 282, 227, 252, 236, 159, 227,  20, 334, 280,
       270, 338,   4, 224, 302,  34, 223, 143, 229,  56, 119,  98, 331,
       134,  56, 273,  69,   8, 237, 117,  14,  86,  15,   1,  38, 229,
        98, 163,   5, 100, 245, 107,  99, 324, 168,  63, 320, 285,  49,
       192, 164,  44, 307, 311, 213,  52,  97,  70, 331, 164, 139, 279,
       244, 320, 257, 193,  77, 115,  24, 236, 169, 139,  98, 186,   7,
       262, 119, 128, 222, 133, 182,  96, 323, 277,  52, 318, 111, 108,
       117,  70, 168, 128,  85, 194, 308,  66, 207, 112, 140, 181,  46,
       170,  26,  35, 293, 192, 316,  89, 115, 251, 256,  11,  6

In [157]:
# np.full()
acm9=np.full((3,20,76),100)
acm9

array([[[100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        ...,
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100]],

       [[100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        ...,
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100]],

       [[100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        ...,
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100]]])

# v.ravel()

In [158]:
a=np.array([[13,24,36,47,59],[55,93,13,82,91]])
a.ravel() # convert any dimensional array in 1d array

array([13, 24, 36, 47, 59, 55, 93, 13, 82, 91])

In [160]:
#np.zeros(), np.ones(), np.empty(),
#np.arange(), np.linspace(), dtype()
a_z=np.zeros(180)
a_z_reshape=a_z.reshape(2,90)
print(a_z_reshape,a_z_reshape.ndim)
print('------------------------------------------')
print(a_z,a_z.ndim)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 2
------------------------------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [161]:
# changes will be in implemented variable not stored in assigned variable
a_z=np.zeros(190)
a_z_resize=a_z.resize(2,95)
print(a_z_resize) # assigned variable
print(a_z) # function implemented variable

None
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [163]:
a_z=np.zeros(150).reshape(2,3,25)
a_z,a_z.ndim

(array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0.]]]),
 3)

In [165]:
'''- np.array(), np.zeros(), np.ones(), np.empty(),

- np.arange(), np.linspace(), np.random.randint(), np.full() dtype()'''
a_o=np.ones(700).reshape(2,2,7,25)
a_o,a_o.ndim

(array([[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
          [1.

In [166]:
'''- np.array(), np.zeros(), np.ones(), np.empty(),

- np.arange(), np.linspace(), np.random.randint(), np.full() dtype()'''
a_o=np.empty(400).reshape(2,8,5,5)
a_o,a_o.ndim

(array([[[[8.47769730e-312, 8.47769730e-312, 8.47769731e-312,
           8.47769731e-312, 8.47769732e-312],
          [8.47769733e-312, 8.47769734e-312, 8.47823346e-312,
           8.47823343e-312, 8.47823311e-312],
          [8.47823311e-312, 8.47823311e-312, 8.47823310e-312,
           8.47823316e-312, 8.47823310e-312],
          [8.47823317e-312, 8.47823333e-312, 8.47823333e-312,
           8.47823330e-312, 8.47823326e-312],
          [8.47823329e-312, 8.47823331e-312, 8.47823325e-312,
           8.47823327e-312, 8.47823327e-312]],
 
         [[8.47823326e-312, 8.47820705e-312, 8.47820706e-312,
           8.47820703e-312, 8.47820705e-312],
          [8.47820703e-312, 8.47820707e-312, 8.47820709e-312,
           8.47820709e-312, 8.47820709e-312],
          [8.47820711e-312, 8.47820710e-312, 8.47820710e-312,
           8.47820708e-312, 8.47820703e-312],
          [8.47820708e-312, 8.47820707e-312, 8.47820703e-312,
           8.47820704e-312, 8.47820706e-312],
          [8.47820706e-31

In [167]:
np.empty(shape = [2,3], dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.]])

# numpy data types

Casting

In [168]:
s=np.array(['patna','sasaram','nalanda'])
s,s.dtype

(array(['patna', 'sasaram', 'nalanda'], dtype='<U7'), dtype('<U7'))

In [172]:
# creating data type with defined data type
n=np.array([121,324,437,864],dtype='S')
print(n)
print(n.dtype)

[b'121' b'324' b'437' b'864']
|S3


In [174]:
# for i, u, f, S, U we can define size as well
a=np.array([12,50,63,54,36,53,73],dtype='i')
a

array([12, 50, 63, 54, 36, 53, 73], dtype=int32)

In [175]:
# sdt = specifying data type
sdt=np.ones(2,dtype=np.int64)
sdt

array([1, 1], dtype=int64)

In [177]:
sdt1=np.arange(30,900,30,dtype=np.int8)
sdt1

array([  30,   60,   90,  120, -106,  -76,  -46,  -16,   14,   44,   74,
        104, -122,  -92,  -62,  -32,   -2,   28,   58,   88,  118, -108,
        -78,  -48,  -18,   12,   42,   72,  102], dtype=int8)

In [179]:
# converting data type on existing arrays - casting
# astype()
# astype()
a=np.array([8.1,5.1,6.2,0])
b=a.astype('i')
c=a.astype(int)
d=a.astype(bool)
print(b)
print(c)
print(d)

[8 5 6 0]
[8 5 6 0]
[ True  True  True False]


# Indexing & Slicing - in 1D,2D,3D, ..nD Array

In [180]:
# 1D Indexing & slicing
a=np.array([42,52,65,75,76,45,22,67,95,95,86,85])
print(a)
print(a[3])
print(a[5])

[42 52 65 75 76 45 22 67 95 95 86 85]
75
45


In [182]:
# 1D slicing
print(a)
print(a[0:12:4])
print(a[0:14:6])

[42 52 65 75 76 45 22 67 95 95 86 85]
[42 76 95]
[42 22]


In [183]:
# 2d array
a=np.array([[42,52,65,75,76,45,22,67,95,95,86,85],[42,52,65,75,76,45,22,67,95,95,86,85]])
a

array([[42, 52, 65, 75, 76, 45, 22, 67, 95, 95, 86, 85],
       [42, 52, 65, 75, 76, 45, 22, 67, 95, 95, 86, 85]])

In [184]:
a.shape,a[[0,0,0,-1],[1,2,-2,-3]]

((2, 12), array([52, 65, 86, 95]))

In [185]:
# 3d array
a=np.array([[[1,3,2,4],[4,2,4,67]],[[1,3,2,4],[4,2,4,67]]])
a.shape,a.ndim,a,

((2, 2, 4),
 3,
 array([[[ 1,  3,  2,  4],
         [ 4,  2,  4, 67]],
 
        [[ 1,  3,  2,  4],
         [ 4,  2,  4, 67]]]))

In [186]:
# advance indexing in 3d
a[[1],[1,0,0],[0,1,3]]

array([4, 3, 4])

In [187]:
# advance slicing in 3d
a,a[1][::,:3]

(array([[[ 1,  3,  2,  4],
         [ 4,  2,  4, 67]],
 
        [[ 1,  3,  2,  4],
         [ 4,  2,  4, 67]]]),
 array([[1, 3, 2],
        [4, 2, 4]]))

In [188]:
import random
a=np.random.randint(0,1000,100).reshape(2,2,5,5) # start,stop,amount
a

array([[[[147, 788, 799, 279,   3],
         [702, 556, 640, 602, 452],
         [414, 789, 772, 119, 289],
         [939, 184, 639, 118, 556],
         [ 89, 864,  79, 320, 843]],

        [[210, 654, 126,  67,  86],
         [ 99, 621, 877, 836, 991],
         [686, 551, 926, 378, 925],
         [835, 385, 868, 816, 858],
         [265, 978,  20, 867, 529]]],


       [[[578, 451, 846, 997, 349],
         [731, 245, 730, 420, 261],
         [259, 552, 151, 835, 780],
         [ 10, 298, 683, 173, 980],
         [737, 694, 301, 995, 735]],

        [[452, 397, 274, 195, 997],
         [569, 623, 707, 565,  66],
         [240, 275,  65, 846, 364],
         [773, 848, 642, 618, 739],
         [191, 367, 732,  21,  76]]]])

In [189]:
a[[1],[1],[2],[3]]

array([846])

In [190]:
a[[0],[1],[2,1,0],[2,0,1]]

array([926,  99, 654])

# Extract Items

In [191]:
s_b=b[b>500]
s_b, type(s_b)

(array([], dtype=int32), numpy.ndarray)

In [192]:
s_c=a[a%2==0]
s_c,a

(array([788, 702, 556, 640, 602, 452, 414, 772, 184, 118, 556, 864, 320,
        210, 654, 126,  86, 836, 686, 926, 378, 868, 816, 858, 978,  20,
        578, 846, 730, 420, 552, 780,  10, 298, 980, 694, 452, 274,  66,
        240, 846, 364, 848, 642, 618, 732,  76]),
 array([[[[147, 788, 799, 279,   3],
          [702, 556, 640, 602, 452],
          [414, 789, 772, 119, 289],
          [939, 184, 639, 118, 556],
          [ 89, 864,  79, 320, 843]],
 
         [[210, 654, 126,  67,  86],
          [ 99, 621, 877, 836, 991],
          [686, 551, 926, 378, 925],
          [835, 385, 868, 816, 858],
          [265, 978,  20, 867, 529]]],
 
 
        [[[578, 451, 846, 997, 349],
          [731, 245, 730, 420, 261],
          [259, 552, 151, 835, 780],
          [ 10, 298, 683, 173, 980],
          [737, 694, 301, 995, 735]],
 
         [[452, 397, 274, 195, 997],
          [569, 623, 707, 565,  66],
          [240, 275,  65, 846, 364],
          [773, 848, 642, 618, 739],
          [191, 

# Sorting, Adding elements 

In [193]:
# create array
a_sort=np.array([[22,11,10,9,33,3,20],[12,31,43,22,55,15,13]])
a_sort

array([[22, 11, 10,  9, 33,  3, 20],
       [12, 31, 43, 22, 55, 15, 13]])

In [194]:
# sort() - assending orders
a_sort.sort()
a_sort

array([[ 3,  9, 10, 11, 20, 22, 33],
       [12, 13, 15, 22, 31, 43, 55]])

In [195]:
a_sort=a_sort[::-1]
a_sort

array([[12, 13, 15, 22, 31, 43, 55],
       [ 3,  9, 10, 11, 20, 22, 33]])

In [196]:
array=np.array([[[22,12,2,5,66,44,87,54],[22,12,2,5,66,44,87,54]],
[[22,12,2,5,66,44,87,54],[22,12,2,5,66,44,87,54]]])
print(array)
# quickly sort the numbers in assending order with:
np.sort(array)

[[[22 12  2  5 66 44 87 54]
  [22 12  2  5 66 44 87 54]]

 [[22 12  2  5 66 44 87 54]
  [22 12  2  5 66 44 87 54]]]


array([[[ 2,  5, 12, 22, 44, 54, 66, 87],
        [ 2,  5, 12, 22, 44, 54, 66, 87]],

       [[ 2,  5, 12, 22, 44, 54, 66, 87],
        [ 2,  5, 12, 22, 44, 54, 66, 87]]])

In [197]:
a,a.argsort()

(array([[[[147, 788, 799, 279,   3],
          [702, 556, 640, 602, 452],
          [414, 789, 772, 119, 289],
          [939, 184, 639, 118, 556],
          [ 89, 864,  79, 320, 843]],
 
         [[210, 654, 126,  67,  86],
          [ 99, 621, 877, 836, 991],
          [686, 551, 926, 378, 925],
          [835, 385, 868, 816, 858],
          [265, 978,  20, 867, 529]]],
 
 
        [[[578, 451, 846, 997, 349],
          [731, 245, 730, 420, 261],
          [259, 552, 151, 835, 780],
          [ 10, 298, 683, 173, 980],
          [737, 694, 301, 995, 735]],
 
         [[452, 397, 274, 195, 997],
          [569, 623, 707, 565,  66],
          [240, 275,  65, 846, 364],
          [773, 848, 642, 618, 739],
          [191, 367, 732,  21,  76]]]]),
 array([[[[4, 0, 3, 1, 2],
          [4, 1, 3, 2, 0],
          [3, 4, 0, 2, 1],
          [3, 1, 4, 2, 0],
          [2, 0, 3, 4, 1]],
 
         [[3, 4, 2, 0, 1],
          [0, 1, 3, 2, 4],
          [3, 1, 0, 4, 2],
          [1, 3, 0, 4, 2]

In [201]:
#a=np.array([[[1,2,3,2,1],[65,4,3,2,3],[1,2,3,2,1],[65,4,3,2,3]],
# [[1,2,98,2,90],[65,4,78,2,3],[1,2,3,2,1],[65,43,3,76,3]]])
a=np.array([[1,2,3,2,1,65,4,3,2,3]])
a.shape,a,np.lexsort(a),a.argsort()

((1, 10),
 array([[ 1,  2,  3,  2,  1, 65,  4,  3,  2,  3]]),
 array([0, 4, 1, 3, 8, 2, 7, 9, 6, 5], dtype=int64),
 array([[0, 4, 1, 3, 8, 2, 7, 9, 6, 5]], dtype=int64))

In [202]:
a.argmax()

5

In [203]:
a.argmin()

0

In [204]:
a[0][5],a[0][0]

(65, 1)

# Operations on Array/Matrix

Array operations

In [205]:
r1 =[[12,13,4],[15,16,1],[18,19,2],[21,2,24]]
a1 = np.asarray(r1)
a1

array([[12, 13,  4],
       [15, 16,  1],
       [18, 19,  2],
       [21,  2, 24]])

In [206]:
a1+20

array([[32, 33, 24],
       [35, 36, 21],
       [38, 39, 22],
       [41, 22, 44]])

In [207]:
a1

array([[12, 13,  4],
       [15, 16,  1],
       [18, 19,  2],
       [21,  2, 24]])

In [208]:
print(a1)
print('------------------')
a1+[[10],[15],[20],[25]] # row

[[12 13  4]
 [15 16  1]
 [18 19  2]
 [21  2 24]]
------------------


array([[22, 23, 14],
       [30, 31, 16],
       [38, 39, 22],
       [46, 27, 49]])

In [209]:
print(a1)
a2 = a1+[[10],[15],[20],[25]]
a2

[[12 13  4]
 [15 16  1]
 [18 19  2]
 [21  2 24]]


array([[22, 23, 14],
       [30, 31, 16],
       [38, 39, 22],
       [46, 27, 49]])

Column wise addition

In [210]:
print(a1)
a1+[10,15,20]

[[12 13  4]
 [15 16  1]
 [18 19  2]
 [21  2 24]]


array([[22, 28, 24],
       [25, 31, 21],
       [28, 34, 22],
       [31, 17, 44]])

# Adding array of same dimension 

In [211]:
print(a1)
a1+[[2,3,4],
[1,4,3],
[2,1,3],
[1,2,4]]

[[12 13  4]
 [15 16  1]
 [18 19  2]
 [21  2 24]]


array([[14, 16,  8],
       [16, 20,  4],
       [20, 20,  5],
       [22,  4, 28]])

In [212]:
a = np.array([[10,20,30],[40,50,60]])
print(a)
print('-------------')
b1 = 10
b2 = np.array([10])
c = np.array([10,10,10])
d = np.array([[10,10,10],[10,10,10]])
print('------------a*b1')
print(a*b1)
print('------------a*b2')
print(a*b2)
print('------------a*c')
print(a*c)
print('------------a*d')
print(a*d)

[[10 20 30]
 [40 50 60]]
-------------
------------a*b1
[[100 200 300]
 [400 500 600]]
------------a*b2
[[100 200 300]
 [400 500 600]]
------------a*c
[[100 200 300]
 [400 500 600]]
------------a*d
[[100 200 300]
 [400 500 600]]


# Numpy array functions

np.sum()

In [213]:
a1

array([[12, 13,  4],
       [15, 16,  1],
       [18, 19,  2],
       [21,  2, 24]])

In [214]:
a.sum()

210

In [215]:
np.sum(a1)

147

In [216]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [217]:
a.sum(axis=0)

array([50, 70, 90])

In [218]:
a.sum(axis=1)

array([ 60, 150])

In [219]:
a=np.array([[[1,2,3,4],[5,6,7,8]],[[11,12,3,4],[5,6,7,88]]])
a,a.argmax()

(array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[11, 12,  3,  4],
         [ 5,  6,  7, 88]]]),
 15)

In [220]:
p1=np.array([[11, 12, 3, 4],[ 5, 6, 7, 88]])
print(np.max(p1))
print(np.min(p1))
p1[1][3]

88
3


88

In [222]:
p2=p1

In [223]:
print(np.argmax(p2,axis=0)) # column wise
print(np.argmin(p2,axis=0)) # column wise
print(np.argmax(p2,axis=1)) # row wise
print(np.argmin(p2,axis=1)) # row wise

[0 0 1 1]
[1 1 0 0]
[1 3]
[2 0]


In [224]:
np.sort(p1)

array([[ 3,  4, 11, 12],
       [ 5,  6,  7, 88]])

In [225]:
p1[::-1],p1

(array([[ 5,  6,  7, 88],
        [11, 12,  3,  4]]),
 array([[11, 12,  3,  4],
        [ 5,  6,  7, 88]]))

In [226]:
# sort row wise
np.sort(p1,axis=1)

array([[ 3,  4, 11, 12],
       [ 5,  6,  7, 88]])

In [227]:
p1,p1[np.where(p1%3==0)]

(array([[11, 12,  3,  4],
        [ 5,  6,  7, 88]]),
 array([12,  3,  6]))

In [228]:
np.where(p1 < 20)

(array([0, 0, 0, 0, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2], dtype=int64))

In [229]:
np.where(p1 < 20,p1, p1*2),p1

(array([[ 11,  12,   3,   4],
        [  5,   6,   7, 176]]),
 array([[11, 12,  3,  4],
        [ 5,  6,  7, 88]]))

In [230]:
np.where(p1%2==0, p1+10, p1-7)

array([[ 4, 22, -4, 14],
       [-2, 16,  0, 98]])

In [231]:
np.where(p1%2==0),p1

((array([0, 0, 1, 1], dtype=int64), array([1, 3, 1, 3], dtype=int64)),
 array([[11, 12,  3,  4],
        [ 5,  6,  7, 88]]))

In [232]:
p1[np.where(p1%2==0)]

array([12,  4,  6, 88])

In [233]:
t1 = np.extract(p1>20, p1)
print(t1,p1)
type(t1)

[88] [[11 12  3  4]
 [ 5  6  7 88]]


numpy.ndarray

In [234]:
np.extract(p1%3!=0,p1)

array([11,  4,  5,  7, 88])

In [235]:
np.insert(p1,2,41),p1

(array([11, 12, 41,  3,  4,  5,  6,  7, 88]),
 array([[11, 12,  3,  4],
        [ 5,  6,  7, 88]]))

In [236]:
p2 = np.delete(p1,4)
p2

array([11, 12,  3,  4,  6,  7, 88])

In [237]:
q1 = np.delete(p1,2,axis=1) # deletes 2nd index column value corresponding to each row
print(q1)

[[11 12  4]
 [ 5  6 88]]


In [238]:
p1

array([[11, 12,  3,  4],
       [ 5,  6,  7, 88]])

In [239]:
q1 = np.delete(p1,1,axis=0) # deletes 2nd index row value corresponding to each column
print(q1)

[[11 12  3  4]]


In [240]:
np.append(p1,23)

array([11, 12,  3,  4,  5,  6,  7, 88, 23])

In [241]:
# Column wise - Add a value to each column, thereby creaing a new row
r2 = np.append(p1, [[13,14,15,16]], axis=0)
print(r2)
print(r2.shape)

[[11 12  3  4]
 [ 5  6  7 88]
 [13 14 15 16]]
(3, 4)


In [242]:
p1,r2

(array([[11, 12,  3,  4],
        [ 5,  6,  7, 88]]),
 array([[11, 12,  3,  4],
        [ 5,  6,  7, 88],
        [13, 14, 15, 16]]))

In [243]:
# Row wise - Add a value to each row, thereby creaing a new column
r4 = np.append(p1, [[500],[600]], axis=1)
print(r4)
print(r4.shape)

[[ 11  12   3   4 500]
 [  5   6   7  88 600]]
(2, 5)


# Iterating over numpy array - np.nditer()

In [249]:
for i in p1:
    print(i)

[11 12  3  4]
[ 5  6  7 88]


In [250]:
p1

array([[11, 12,  3,  4],
       [ 5,  6,  7, 88]])

In [251]:
for i in np.nditer(p1):
    print(i)

11
12
3
4
5
6
7
88


In [252]:
n1=np.arange(9).reshape(3,3)
n1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [253]:
# Add 0th column and 1st column
res1 = n1[:,0]+ n1[:,1] # Element wise addition of 1st column and 2nd column
print(res1)
res2 = n1[:,0].sum() + n1[:,1].sum() # Aggregate sum of all elements of 1st and 2nd column
print(res2)
res3 = n1[0] + n1[1] # sum of 0th and 1st row
print(res3)
res4 = n1[0].sum() + n1[1].sum() # Aggreate sum of 1st and 2nd row
print(res4)

[ 1  7 13]
21
[3 5 7]
15


In [254]:
for i in n1:
    print(i)
for i in np.nditer(n1):
    print(i,end=" ")
for i in n1:
    print(i,end=" ")
    print(len(n1))
for i in range(len(n1)):
    print(n1[i],end=" ")

[0 1 2]
[3 4 5]
[6 7 8]
0 1 2 3 4 5 6 7 8 [0 1 2] 3
[3 4 5] 3
[6 7 8] 3
[0 1 2] [3 4 5] [6 7 8] 

In [255]:
n1.flatten()
for i in n1.flatten():
    print(i)

0
1
2
3
4
5
6
7
8


In [256]:
for i in np.nditer(n1):
    print(i,end=' ')
for i in np.nditer(n1,order='C'): # order= 'C', iterates element row wise
    print(i,end=' ')
n1
for i in np.nditer(n1,order='F'): # order= 'F', print element column wise
    print(i,end=' ')
n1
for i in np.nditer(n1,order='A'): # order= 'A', print element column wise
    print(i,end=' ')
for i in np.nditer(n1,order='K'): # order= 'K', print element column wise
    print(i,end=' ')
n1

0 1 2 3 4 5 6 7 8 0 1 2 3 4 5 6 7 8 0 3 6 1 4 7 2 5 8 0 1 2 3 4 5 6 7 8 0 1 2 3 4 5 6 7 8 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [257]:
n2=np.arange(9).reshape(3,3)
for x,y in np.nditer([n1,n2]):
    print(x,y)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8


In [258]:
## 5) Matrix Multiplication and Transpose, Flatten

r1 = np.arange(2,20,2).reshape(3,3)
print(r1) # Normal matrix
print(r1.T) # Transpose of the array
print(r1.flatten()) # Flatten the normal array
print(r1.T.flatten()) # Flatten the transpose of the array
a1 = np.array([8,5,0,2,9,6,4,1,7]).reshape(3,3)
a2 = np.array([3,7,9,4,1,0,5,6,2]).reshape(3,3)
print(a1)
print(a2)
# Actual Matrix multiplication
r2 = np.matmul(a1,a2)
print(r2)
# Actual Matrix multiplication
r2 = np.dot(a1,a2)
print(r2)
print(a1)
print(a2)
# Element wise multiplication
r3 = np.multiply(a1,a2)
print(r3)
#<b>Linear algebra in NumPy:</b>
#<br>The Linear Algebra module of NumPy offers various methods to apply linear algebra
#on any numpy array. It can be used to determine:
#<ol>
#<li>rank, determinant, trace, etc. of an array.</li>
#<li>solve linear equations</li>
#</ol>
A = np.array([[0,1,2],
[2,3,4],
[1,2,5]],dtype=int)
print(A)
print("Rank of A:", np.linalg.matrix_rank(A))
print("Trace of A:", np.trace(A)) # 0+3+5
print("Determinant of A:", np.linalg.det(A))
# 0(3*5-4*2) - 1(2*5 - 4*1) + 2(2*2 - 3*1) = -6 + 2(1) = -6 + 2 = -4
print("Inverse of A:\n", np.linalg.inv(A))
### Solving Linear Equations using numpy
# Solving the equation:-
# x -2y = 8
# 3x + 4y = 18
a = np.array([[1, -2], [3, 4]])
b = np.array([8, 18])
print("Solution of linear equations:", np.linalg.solve(a, b))
# Solving the equation:-
# x +2y-z =9
# 2x -3y+7z = 15
# 7x -4y-5z = 13
a = np.array([[1, 2, -1], [2, -3, 7], [7, -4, -5]])
b = np.array([9,15,13])
x = np.linalg.solve(a, b)
print(x)
s1 = np.array([[0,1,2],[2,3,4],[0,2,1]])
print(s1)
print("Determinant of A:", np.linalg.det(s1))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
[ 2  4  6  8 10 12 14 16 18]
[ 2  8 14  4 10 16  6 12 18]
[[8 5 0]
 [2 9 6]
 [4 1 7]]
[[3 7 9]
 [4 1 0]
 [5 6 2]]
[[44 61 72]
 [72 59 30]
 [51 71 50]]
[[44 61 72]
 [72 59 30]
 [51 71 50]]
[[8 5 0]
 [2 9 6]
 [4 1 7]]
[[3 7 9]
 [4 1 0]
 [5 6 2]]
[[24 35  0]
 [ 8  9  0]
 [20  6 14]]
[[0 1 2]
 [2 3 4]
 [1 2 5]]
Rank of A: 3
Trace of A: 8
Determinant of A: -4.0
Inverse of A:
 [[-1.75  0.25  0.5 ]
 [ 1.5   0.5  -1.  ]
 [-0.25 -0.25  0.5 ]]
Solution of linear equations: [ 6.8 -0.6]
[5. 3. 2.]
[[0 1 2]
 [2 3 4]
 [0 2 1]]
Determinant of A: 6.0


# Concatenation

In [260]:
# creating two 1D array
arr_1=np.array([15,42,63,74,85])
arr_2=np.array([12,33,54,115,616])
print(arr)
arr_1,arr_2

[100 322 343 711 430  56  40]


(array([15, 42, 63, 74, 85]), array([ 12,  33,  54, 115, 616]))

In [261]:
arr_1+arr_2

array([ 27,  75, 117, 189, 701])

In [262]:
arr_1_2=np.concatenate((arr_1,arr_2)) # use double paranthesis
arr_1_2

array([ 15,  42,  63,  74,  85,  12,  33,  54, 115, 616])

In [263]:
arr_2_1=np.concatenate((arr_2,arr_1),axis=0) # use double paranthesis
arr_2_1

array([ 12,  33,  54, 115, 616,  15,  42,  63,  74,  85])

In [264]:
import random
a=np.random.randint(10,100,50).reshape(2,5,5)
a

array([[[77, 34, 26, 92, 94],
        [97, 82, 97, 36, 30],
        [95, 57, 71, 42, 38],
        [55, 82, 37, 31, 52],
        [36, 33, 43, 90, 80]],

       [[68, 96, 57, 17, 25],
        [91, 22, 73, 43, 46],
        [22, 11, 98, 78, 67],
        [56, 68, 37, 91, 26],
        [46, 47, 52, 53, 59]]])

In [265]:
b=np.random.randint(100,1000,50).reshape(2,5,5)
b

array([[[603, 999, 338, 131, 947],
        [707, 336, 523, 166, 867],
        [954, 571, 734, 679, 236],
        [337, 107, 414, 974, 622],
        [288, 303, 761, 348, 956]],

       [[507, 199, 283, 248, 331],
        [125, 165, 366, 383, 771],
        [739, 640, 102, 259, 197],
        [375, 166, 625, 916, 247],
        [617, 288, 876, 768, 654]]])

In [266]:
c_=np.concatenate((a,b)) # by defalt - # axis =0 rows wise horizontally
c_

array([[[ 77,  34,  26,  92,  94],
        [ 97,  82,  97,  36,  30],
        [ 95,  57,  71,  42,  38],
        [ 55,  82,  37,  31,  52],
        [ 36,  33,  43,  90,  80]],

       [[ 68,  96,  57,  17,  25],
        [ 91,  22,  73,  43,  46],
        [ 22,  11,  98,  78,  67],
        [ 56,  68,  37,  91,  26],
        [ 46,  47,  52,  53,  59]],

       [[603, 999, 338, 131, 947],
        [707, 336, 523, 166, 867],
        [954, 571, 734, 679, 236],
        [337, 107, 414, 974, 622],
        [288, 303, 761, 348, 956]],

       [[507, 199, 283, 248, 331],
        [125, 165, 366, 383, 771],
        [739, 640, 102, 259, 197],
        [375, 166, 625, 916, 247],
        [617, 288, 876, 768, 654]]])

In [267]:
d_=np.concatenate((b,a),axis=1) # # axis =1 column wise vertically in numpy
d_

array([[[603, 999, 338, 131, 947],
        [707, 336, 523, 166, 867],
        [954, 571, 734, 679, 236],
        [337, 107, 414, 974, 622],
        [288, 303, 761, 348, 956],
        [ 77,  34,  26,  92,  94],
        [ 97,  82,  97,  36,  30],
        [ 95,  57,  71,  42,  38],
        [ 55,  82,  37,  31,  52],
        [ 36,  33,  43,  90,  80]],

       [[507, 199, 283, 248, 331],
        [125, 165, 366, 383, 771],
        [739, 640, 102, 259, 197],
        [375, 166, 625, 916, 247],
        [617, 288, 876, 768, 654],
        [ 68,  96,  57,  17,  25],
        [ 91,  22,  73,  43,  46],
        [ 22,  11,  98,  78,  67],
        [ 56,  68,  37,  91,  26],
        [ 46,  47,  52,  53,  59]]])

# Stack

In [268]:
a=np.random.randint(100,1000,10).reshape(2,5)
b=np.random.randint(200,2000,10).reshape(2,5)
a,b

(array([[212, 185, 510, 260, 317],
        [896, 268, 367, 697, 449]]),
 array([[ 492, 1615, 1306, 1345, 1059],
        [ 538,  992, 1043, 1770,  300]]))

In [269]:
np.stack((a,b))

array([[[ 212,  185,  510,  260,  317],
        [ 896,  268,  367,  697,  449]],

       [[ 492, 1615, 1306, 1345, 1059],
        [ 538,  992, 1043, 1770,  300]]])

In [270]:
np.hstack((a,b))

array([[ 212,  185,  510,  260,  317,  492, 1615, 1306, 1345, 1059],
       [ 896,  268,  367,  697,  449,  538,  992, 1043, 1770,  300]])

In [271]:
np.vstack((a,b))

array([[ 212,  185,  510,  260,  317],
       [ 896,  268,  367,  697,  449],
       [ 492, 1615, 1306, 1345, 1059],
       [ 538,  992, 1043, 1770,  300]])

In [272]:
np.stack((a,b),axis=0)

array([[[ 212,  185,  510,  260,  317],
        [ 896,  268,  367,  697,  449]],

       [[ 492, 1615, 1306, 1345, 1059],
        [ 538,  992, 1043, 1770,  300]]])

In [273]:
np.stack((a,b),axis=1)

array([[[ 212,  185,  510,  260,  317],
        [ 492, 1615, 1306, 1345, 1059]],

       [[ 896,  268,  367,  697,  449],
        [ 538,  992, 1043, 1770,  300]]])

In [274]:
np.stack((a,b),axis=2)

array([[[ 212,  492],
        [ 185, 1615],
        [ 510, 1306],
        [ 260, 1345],
        [ 317, 1059]],

       [[ 896,  538],
        [ 268,  992],
        [ 367, 1043],
        [ 697, 1770],
        [ 449,  300]]])

In [276]:
np.stack((a,b),axis=2)

array([[[ 212,  492],
        [ 185, 1615],
        [ 510, 1306],
        [ 260, 1345],
        [ 317, 1059]],

       [[ 896,  538],
        [ 268,  992],
        [ 367, 1043],
        [ 697, 1770],
        [ 449,  300]]])

# intersaction & difference

In [277]:
a=np.array([[[10,20,30,40,50],[60,70,80,90,100]],[[10,20,30,40,50],[60,70,80,90,100]]])
b=np.array([[[20,40,50],[60,70,80]],[[20,40,50],[60,70,80]]])
a,b

(array([[[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]],
 
        [[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]]]),
 array([[[20, 40, 50],
         [60, 70, 80]],
 
        [[20, 40, 50],
         [60, 70, 80]]]))

In [278]:
np.intersect1d(a,b)

array([20, 40, 50, 60, 70, 80])

In [279]:
np.setdiff1d(a,b)

array([ 10,  30,  90, 100])

# Numpy array copy vs View

In [280]:
a.shape,a

((2, 2, 5),
 array([[[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]],
 
        [[ 10,  20,  30,  40,  50],
         [ 60,  70,  80,  90, 100]]]))

In [281]:
a[0][[0],[3]]=300
a

array([[[ 10,  20,  30, 300,  50],
        [ 60,  70,  80,  90, 100]],

       [[ 10,  20,  30,  40,  50],
        [ 60,  70,  80,  90, 100]]])

In [282]:
a[1][[0],[4]]=345
a

array([[[ 10,  20,  30, 300,  50],
        [ 60,  70,  80,  90, 100]],

       [[ 10,  20,  30,  40, 345],
        [ 60,  70,  80,  90, 100]]])

In [283]:
# view
a=np.array([[1,22,33,66],
[22,44,55,87]])
v=a.view()
v
a[0][3]=876
a,v

(array([[  1,  22,  33, 876],
        [ 22,  44,  55,  87]]),
 array([[  1,  22,  33, 876],
        [ 22,  44,  55,  87]]))

In [284]:
# copy
c=a.copy()
c
a[1][3]=1000
c,a

(array([[  1,  22,  33, 876],
        [ 22,  44,  55,  87]]),
 array([[   1,   22,   33,  876],
        [  22,   44,   55, 1000]]))

In [286]:
import random
import numpy as np
import pandas as pd
aa=np.random.rand(100).reshape(2,50)
#pd.DataFrame(aa)
aa

array([[0.15720485, 0.63668881, 0.16530257, 0.79873743, 0.5952118 ,
        0.78391188, 0.1450279 , 0.79541024, 0.52466841, 0.4763643 ,
        0.89052506, 0.87276926, 0.63471616, 0.52250258, 0.07363221,
        0.75152622, 0.38798775, 0.41367975, 0.67223794, 0.68367181,
        0.95304489, 0.61676842, 0.64118926, 0.11959984, 0.21168668,
        0.53857469, 0.59126288, 0.70738581, 0.07352876, 0.79248256,
        0.39786016, 0.14587433, 0.08093412, 0.01181228, 0.92424506,
        0.34336572, 0.10524528, 0.9005876 , 0.8282239 , 0.02528769,
        0.54266898, 0.6356883 , 0.37281425, 0.16585797, 0.93540406,
        0.79781425, 0.45331501, 0.99309036, 0.77386814, 0.38338383],
       [0.58654127, 0.74903373, 0.10575224, 0.18900663, 0.29381042,
        0.95565382, 0.13337459, 0.53236906, 0.30247839, 0.09344349,
        0.15581259, 0.75904675, 0.06360162, 0.3982422 , 0.87703617,
        0.55164411, 0.85862897, 0.47177814, 0.48383026, 0.88868628,
        0.05706608, 0.35672589, 0.62724296, 0.7

In [287]:
np.ones(40)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [290]:
a=1
l=[1,2,3,4]
#for i in range(0):
if a in l:
    print('n',i)

n 8


In [291]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [292]:
a=np.array([[[1,2]],[[1,2]],[[1,2]]])
a.ndim

3

# Akash Kumar
Truba College Of Science & Technology
Enrollment No. 0533CL211001